export const ADD_SUMMONER = 'ADD_SUMMONER';
export const LOAD_SUMMONERS = 'LOAD_SUMMONERS';
export const CLEAR_SUMMONERS = 'CLEAR_SUMMONERS';
export const LOAD_MATCH_DATA = 'LOAD_MATCH_DATA';
export const LOAD_MASTERY_DATA = 'LOAD_MASTERY_DATA';
export const LOAD_RUNE_DATA = 'LOAD_RUNE_DATA';
export const CHANGE_VIEW = 'CHANGE_VIEW';
