export const ADD_SUMMONER = 'ADD_SUMMONER';
export const LOAD_SUMMONERS = 'LOAD_SUMMONERS';
export const DELETE_SUMMONER = 'DELETE_SUMMONER';
export const LOAD_MATCH_DATA_AND_CHANGE_VIEW = 'LOAD_MATCH_DATA_AND_CHANGE_VIEW';
export const LOAD_MATCH_PLAYER_RANKS = 'LOAD_MATCH_PLAYER_RANKS';
export const LOAD_MASTERY_DATA = 'LOAD_MASTERY_DATA';
export const LOAD_RUNE_DATA = 'LOAD_RUNE_DATA';
export const CHANGE_VIEW = 'CHANGE_VIEW';
